/**
 * Core low-level libssh2 wrapper exports
 * 
 * This module exports the low-level Session and Channel classes
 * that provide direct access to libssh2 functionality without
 * any high-level abstractions or application logic.
 */

// Core classes
export { Session } from './session.js';
export { Channel } from './channel.js';
export { SFTP, LIBSSH2_FXF_READ, LIBSSH2_FXF_WRITE, LIBSSH2_FXF_APPEND, LIBSSH2_FXF_CREAT, LIBSSH2_FXF_TRUNC, LIBSSH2_FXF_EXCL } from './sftp.js';
export { SFTPHandle, SFTPAttributes, SFTPStatVFS } from './sftp-handle.js';
export { Agent, createAgent } from './agent.js';
export { KnownHost, KnownHostEntry, createKnownHost } from './knownhost.js';
export { Listener } from './listener.js';

// FFI utilities and constants
export {
  loadlibssh2,
  cstr,
  readCString,
  isNull,
  // Error codes
  LIBSSH2_ERROR_NONE,
  LIBSSH2_ERROR_SOCKET_NONE,
  LIBSSH2_ERROR_BANNER_RECV,
  LIBSSH2_ERROR_BANNER_SEND,
  LIBSSH2_ERROR_INVALID_MAC,
  LIBSSH2_ERROR_KEX_FAILURE,
  LIBSSH2_ERROR_ALLOC,
  LIBSSH2_ERROR_SOCKET_SEND,
  LIBSSH2_ERROR_KEY_EXCHANGE_FAILURE,
  LIBSSH2_ERROR_TIMEOUT,
  LIBSSH2_ERROR_HOSTKEY_INIT,
  LIBSSH2_ERROR_HOSTKEY_SIGN,
  LIBSSH2_ERROR_DECRYPT,
  LIBSSH2_ERROR_SOCKET_DISCONNECT,
  LIBSSH2_ERROR_PROTO,
  LIBSSH2_ERROR_PASSWORD_EXPIRED,
  LIBSSH2_ERROR_FILE,
  LIBSSH2_ERROR_METHOD_NONE,
  LIBSSH2_ERROR_AUTHENTICATION_FAILED,
  LIBSSH2_ERROR_PUBLICKEY_UNVERIFIED,
  LIBSSH2_ERROR_CHANNEL_OUTOFORDER,
  LIBSSH2_ERROR_CHANNEL_FAILURE,
  LIBSSH2_ERROR_CHANNEL_REQUEST_DENIED,
  LIBSSH2_ERROR_CHANNEL_UNKNOWN,
  LIBSSH2_ERROR_CHANNEL_WINDOW_EXCEEDED,
  LIBSSH2_ERROR_CHANNEL_PACKET_EXCEEDED,
  LIBSSH2_ERROR_CHANNEL_CLOSED,
  LIBSSH2_ERROR_CHANNEL_EOF_SENT,
  LIBSSH2_ERROR_SCP_PROTOCOL,
  LIBSSH2_ERROR_ZLIB,
  LIBSSH2_ERROR_SOCKET_TIMEOUT,
  LIBSSH2_ERROR_SFTP_PROTOCOL,
  LIBSSH2_ERROR_REQUEST_DENIED,
  LIBSSH2_ERROR_METHOD_NOT_SUPPORTED,
  LIBSSH2_ERROR_INVAL,
  LIBSSH2_ERROR_INVALID_POLL_TYPE,
  LIBSSH2_ERROR_PUBLICKEY_PROTOCOL,
  LIBSSH2_ERROR_EAGAIN,
  LIBSSH2_ERROR_BUFFER_TOO_SMALL,
  LIBSSH2_ERROR_BAD_USE,
  LIBSSH2_ERROR_COMPRESS,
  LIBSSH2_ERROR_OUT_OF_BOUNDARY,
  LIBSSH2_ERROR_AGENT_PROTOCOL,
  LIBSSH2_ERROR_SOCKET_RECV,
  LIBSSH2_ERROR_ENCRYPT,
  LIBSSH2_ERROR_BAD_SOCKET,
  LIBSSH2_ERROR_KNOWN_HOSTS,
  // Session constants
  LIBSSH2_SESSION_BLOCK_INBOUND,
  LIBSSH2_SESSION_BLOCK_OUTBOUND,
  // Hostkey constants
  LIBSSH2_HOSTKEY_HASH_MD5,
  LIBSSH2_HOSTKEY_HASH_SHA1,
  LIBSSH2_HOSTKEY_HASH_SHA256,
  LIBSSH2_HOSTKEY_TYPE_UNKNOWN,
  LIBSSH2_HOSTKEY_TYPE_RSA,
  LIBSSH2_HOSTKEY_TYPE_DSS,
  LIBSSH2_HOSTKEY_TYPE_ECDSA_256,
  LIBSSH2_HOSTKEY_TYPE_ECDSA_384,
  LIBSSH2_HOSTKEY_TYPE_ECDSA_521,
  LIBSSH2_HOSTKEY_TYPE_ED25519,
  // Stream constants
  SSH_EXTENDED_DATA_STDERR
} from './ffi.js';
